/* Generated By:JJTree: Do not edit this line. ASTAdditive.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sjtu.simpl.grammar;

public
class ASTAdditive extends SimpleNode {
  public ASTAdditive(int id) {
    super(id);
  }

  public ASTAdditive(SimPL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=96499476dd27a0c72bfe533543c4a24f (do not edit this line) */
