/* Generated By:JJTree: Do not edit this line. ASTBopELB.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sjtu.simpl.grammar;

public
class ASTBopELB extends SimpleNode {
  public ASTBopELB(int id) {
    super(id);
  }

  public ASTBopELB(SimPL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=73d59033fe35e591693d6c3627eae5e6 (do not edit this line) */
