/* Generated By:JJTree: Do not edit this line. ASTBopAndOr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sjtu.simpl.grammar;

public
class ASTBopAndOr extends SimpleNode {
  public ASTBopAndOr(int id) {
    super(id);
  }

  public ASTBopAndOr(SimPL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bfdc4d04bca3e1c20cec9f984c3b2db7 (do not edit this line) */
