/* Generated By:JJTree: Do not edit this line. ASTBopELM.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sjtu.simpl.grammar;

public
class ASTBopELM extends SimpleNode {
  public ASTBopELM(int id) {
    super(id);
  }

  public ASTBopELM(SimPL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e8c2ffb84f98b62026ce87179a16b2b2 (do not edit this line) */
