/* Generated By:JJTree: Do not edit this line. ASTDevideOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sjtu.simpl.grammar;

public
class ASTDevideOp extends SimpleNode {
  public ASTDevideOp(int id) {
    super(id);
  }

  public ASTDevideOp(SimPL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimPLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6ca0d69a6b468872fa142371fc98ca30 (do not edit this line) */
