/* Generated By:JJTree: Do not edit this line. ASTExpTerm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sjtu.simpl.grammar;

public
class ASTExpTerm extends SimpleNode {
  public ASTExpTerm(int id) {
    super(id);
  }

  public ASTExpTerm(SimPL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2494e290743d498da1054d2c22c95bdd (do not edit this line) */
