/* Generated By:JJTree: Do not edit this line. ASTMultiExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sjtu.simpl.grammar;

public
class ASTMultiExp extends SimpleNode {
  public ASTMultiExp(int id) {
    super(id);
  }

  public ASTMultiExp(SimPL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=574a53d4b56b799f1d18afa3bf66f0f4 (do not edit this line) */
