/* Generated By:JJTree: Do not edit this line. ASTMultiveExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sjtu.simpl.grammar;

public
class ASTMultiveExp extends SimpleNode {
  public ASTMultiveExp(int id) {
    super(id);
  }

  public ASTMultiveExp(SimPL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimPLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5c554a6da0afb9e34f38caa87dfa0024 (do not edit this line) */
