/* Generated By:JJTree: Do not edit this line. ASTSequence.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sjtu.simpl.grammar;

public
class ASTSequence extends SimpleNode {
  public ASTSequence(int id) {
    super(id);
  }

  public ASTSequence(SimPL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=127778ed873dc3828bacad11effe9004 (do not edit this line) */
