/* Generated By:JJTree: Do not edit this line. ASTTimesOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.sjtu.simpl.grammar;

public
class ASTTimesOp extends SimpleNode {
  public ASTTimesOp(int id) {
    super(id);
  }

  public ASTTimesOp(SimPL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimPLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=10ab0f3a47c9ac7ecc594e6a1f0116c3 (do not edit this line) */
