/* Generated By:JavaCC: Do not edit this line. SimPLVisitor.java Version 5.0 */
package edu.sjtu.simpl.grammar;

public interface SimPLVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTSequence node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTList node, Object data);
  public Object visit(ASTAndOrExpr node, Object data);
  public Object visit(ASTELBExpr node, Object data);
  public Object visit(ASTAdditiveExp node, Object data);
  public Object visit(ASTMultiveExp node, Object data);
  public Object visit(ASTExpTerm node, Object data);
  public Object visit(ASTLeftParenthness node, Object data);
  public Object visit(ASTBracketTail node, Object data);
  public Object visit(ASTPairTail node, Object data);
  public Object visit(ASTApplicationTail node, Object data);
  public Object visit(ASTUopExp node, Object data);
  public Object visit(ASTConditionalExp node, Object data);
  public Object visit(ASTLetExp node, Object data);
  public Object visit(ASTWhileLoopExp node, Object data);
  public Object visit(ASTFstExp node, Object data);
  public Object visit(ASTSndExp node, Object data);
  public Object visit(ASTHeadExp node, Object data);
  public Object visit(ASTTailExp node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTValue node, Object data);
  public Object visit(ASTAnonymousFun node, Object data);
  public Object visit(ASTIntValue node, Object data);
  public Object visit(ASTBoolValue node, Object data);
  public Object visit(ASTNilValue node, Object data);
  public Object visit(ASTNopValue node, Object data);
  public Object visit(ASTAndOp node, Object data);
  public Object visit(ASTOrOp node, Object data);
  public Object visit(ASTBiggerOp node, Object data);
  public Object visit(ASTLessOp node, Object data);
  public Object visit(ASTEqualOp node, Object data);
  public Object visit(ASTPlusOp node, Object data);
  public Object visit(ASTMinusOp node, Object data);
  public Object visit(ASTTimesOp node, Object data);
  public Object visit(ASTDevideOp node, Object data);
  public Object visit(ASTNegationOp node, Object data);
  public Object visit(ASTNotOp node, Object data);
}
/* JavaCC - OriginalChecksum=ba0335b8010181e83502599f6b7dc58c (do not edit this line) */
