package edu.sjtu.simpl.validate;

import edu.sjtu.simpl.exception.SimPLNotDefinedException;
import edu.sjtu.simpl.exception.SimPLTypeException;
import edu.sjtu.simpl.syntax.AnonymousFunction;
import edu.sjtu.simpl.syntax.Application;
import edu.sjtu.simpl.syntax.Assignment;
import edu.sjtu.simpl.syntax.BinaryOperation;
import edu.sjtu.simpl.syntax.BoolValue;
import edu.sjtu.simpl.syntax.Bracket;
import edu.sjtu.simpl.syntax.Expression;
import edu.sjtu.simpl.syntax.First;
import edu.sjtu.simpl.syntax.Head;
import edu.sjtu.simpl.syntax.IfThenElse;
import edu.sjtu.simpl.syntax.IntValue;
import edu.sjtu.simpl.syntax.LetInEnd;
import edu.sjtu.simpl.syntax.List;
import edu.sjtu.simpl.syntax.Nil;
import edu.sjtu.simpl.syntax.Nop;
import edu.sjtu.simpl.syntax.Pair;
import edu.sjtu.simpl.syntax.Second;
import edu.sjtu.simpl.syntax.Sequence;
import edu.sjtu.simpl.syntax.Tail;
import edu.sjtu.simpl.syntax.UnaryOperation;
import edu.sjtu.simpl.syntax.Value;
import edu.sjtu.simpl.syntax.Variable;
import edu.sjtu.simpl.syntax.WhileDoEnd;
import edu.sjtu.simpl.type.Type;

public interface IComplieTimeValidator {
	public Type V( Expression e, TypeMap tm)throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( AnonymousFunction fun, TypeMap tm)throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( Application app, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( Assignment assign, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( BinaryOperation bop, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( BoolValue bv, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( Bracket brket, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( First fst, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( Head head, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( IfThenElse ite, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( IntValue intValue, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( LetInEnd letin, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( List list, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( Nil nil, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( Nop nop, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( Pair pair, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( Second scd, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( Sequence seq, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( Tail tail, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( UnaryOperation uop, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( Value v, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( Variable var, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
	public Type V( WhileDoEnd wde, TypeMap tm) throws SimPLNotDefinedException, SimPLTypeException;
}
